#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Building before pushing'

npm run build ||
    (
        echo '❌ Build failed ❌
            Next build failed: View the errors above to see why.'
        false
    )

# If everything passes... Now we can push
echo '✅ Pushing changes now... ✅'